spring:
  application:
    name: sepsis-alert-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bathtech_sepsis
    username: ${DB_USERNAME:bathtech}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  level:
    com.bathtech.sepsis: INFO
    org.springframework: WARN
